/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Planet(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/planet.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes['Polyhedron_&_Polyhedron_1_&_Polyhedron_2_&_Polyhedron_3_&_Polyhedron_4_&_Polyhedron_5_&_Polyhedron_6_&_Polyhedron_7']
            .geometry
        }
        material={materials.Planet}
        position={[0, 0.05, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.001}
        material-color={props.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials.Ring}
        position={[0, 0.04, 0]}
        rotation={[-1.85663235, -0.38210535, -0.10424403]}
        scale={[0.001, 0.001, 0.0000864]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Particles__Baked.geometry}
        material={materials['Particles 2']}
        position={[-0.00045697, -0.00165996, 0.00003368]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.001}
      />
    </group>
  )
}

useGLTF.preload('/planet.glb')
